### ISSUE TITLE
Popup menus in Gnome Shell aligned incorrectly

### ISSUE THREAD

**Issue by amezin** [NicoHood/arc-theme#108]
Not sure if it is a bug or just a design element that I don't like.

Left border of the popup menu is exactly above the center of the button. It feels very inconvenient (I 
click on the button, move the mouse straight up -> the pointer is outside of the menu). It happens with all small (narrow) menus.

![arc_menu_offset](https://user-images.githubusercontent.com/1273397/44370922-2a1d1e80-a4fe-11e8-95ec-7dc537358839.png)

![adwaita_menu](https://user-images.githubusercontent.com/1273397/44370915-22f61080-a4fe-11e8-8f84-a0b78e0afe0c.png)

- Distribution: Arch Linux
- Desktop environment: gnome-shell 3.28.3+7+g721ce5403-1
- Arc version/commit: arc-gtk-theme 20180715-1
- GTK+ 3 version: gtk3 3.22.30-1
  - Murrine engine version: gtk-engine-murrine 0.98.2-3
  - `gnome-themes-standard` version: no separate "gnome-themes-standard" package
- Installation method (package or source): package

**Comment by NicoHood** [comment]
The first screenshot demonstrates your issue, the 2nd one is taken from where?

I have got the same setup (archlinux, gnome) and for me it looks like the 2nd screenshot. So what is the problem with that?

**Comment by amezin** [comment]
Yes, first screenshot demonstrates the issue. 2nd one - exactly the same setup (extensions), but with default Gnome shell theme.

It may look like 2nd screenshot for you if the layout indicator is closer to the screen edge, and then popup menu position is adjusted to keep it on screen.

Another example, "Places status indicator" extension (from standard gnome-shell-extensions):
![places-arc](https://user-images.githubusercontent.com/1273397/44631765-98e0f880-a992-11e8-800d-a478aeaa3931.png)
![places-default](https://user-images.githubusercontent.com/1273397/44631766-98e0f880-a992-11e8-808a-ab82f100896e.png)

With Arc theme, menu's left edge is aligned exactly with the center of the button (between "a" and "c"). With default theme, menu's left edge is positioned under "l".

> So what is the problem with that?

When I click on a button, usually its somewhere near the center. Then I move the mouse straight up/down (depending on the layout/panel location). With the default theme, I will hit the menu. With Arc, I won't.

Also, for example, the same screenshot with "Adapta" theme:
![places-adapta](https://user-images.githubusercontent.com/1273397/44631927-b020e580-a994-11e8-8277-e7b30009205c.png)
Even better than the default theme, menu's left edge is under "P" (but unfortunately I don't like the rest of the theme)

**Comment by francescoboc** [comment]
+1 I have the same issue
![image](https://user-images.githubusercontent.com/33369475/52522149-9b55b700-2c81-11e9-93ea-700b295fe423.png)

**Comment by r34gzilla** [comment]
+1 Same issue here.
![grafik](https://user-images.githubusercontent.com/21910440/56774952-221c2980-67c5-11e9-8d2e-15597208c3ca.png)

Affected element is probably ".panel-menu". Maybe ".popup-menu-boxpointer" and ".candidate-popup-boxpointer" ("-arrow-base" attribute?) Are also involved. However, being unfamiliar with GNOME themes, I could not find a solution to this problem. Other themes (e.g., "Adapta") are not affected by this issue. Maybe this information is helpful to someone else, so the theme can be fixed.

**Comment by r34gzilla** [comment]
So I have looked something deeper in the gnome-shell code. As i understand it right this cannot be fixed satisfactory in theme "code". Gnome-Shell aligns these popup menus to the center of the button in panel. In detail there is an invisible (in arc theme) arrow as seen in default gnome theme or in this screenshot that is aligned to the center:
![grafik](https://user-images.githubusercontent.com/21910440/56836379-60722100-6877-11e9-8f11-2ab937c19853.png)

We could use the -arrow-base attribute in theme like follows to match the left border of popup with the left border of the button in the panel:
 
.popup-menu-boxpointer {
    -arrow-base: 48px;
}

So it has to be set to the width of the button in the panel. But there is a problem: as the width of these buttons varies by caption we cannot know the exact value at "compile time". In my knowledge there is no way to get the value at runtime in sass/css.

So if we would set this attribute to a fixed value like "48px" may work more or less with some buttons but it would not be perfect as you can see here:
![grafik](https://user-images.githubusercontent.com/21910440/56836387-66680200-6877-11e9-8fa7-fea078add1f2.png)
![grafik](https://user-images.githubusercontent.com/21910440/56836361-505a4180-6877-11e9-9d2d-1a412f57ec3a.png)

**Comment by NicoHood** [comment]
> So if we would set this attribute to a fixed value like "48px" it may work more or less with some buttons but it would not be perfect as you can see here (in adapta theme it is done like this):

If you say "more or less", well then the other themes also work like "this", right? So we have the same behavior, even if its not perfect, but as close as we can get, correct? That sound good to me, would you open a PR for that?

**Comment by drakkar1969** [comment]
Think this issue can be closed based on #240

**Comment by qwertychouskie** [comment]
Are your sure?  I don't think this issue was `border-image` related.  @r34gzilla Could you test this?

**Comment by r34gzilla** [comment]
This issue is "fixed" in master in the way i wrote before. So it's more a workaround than a perfect fix. Another solution i would suggest would look like this:
![grafik](https://user-images.githubusercontent.com/21910440/57794995-36f53880-7745-11e9-8f8e-a61e23d1ffe1.png)

But there is also a Problem that i did not investigated in detail so far: There is no shadow for popups.
This solution would be also more consistently with GTK3-Theme:
![grafik](https://user-images.githubusercontent.com/21910440/57795199-a8cd8200-7745-11e9-8526-548b59216b96.png)

**Comment by drakkar1969** [comment]
@qwertychouskie the issue is not `border-image` related, you're correct. However, when fixing popup menus I also changed the `-arrow-base` property of the menu boxpointer, as highlighted by r34gzilla (the value I used is the same as in the default shell theme). As @NicoHood mentioned above, this is what other themes also do, and no way to always perfectly center given the variable width of buttons. The actual arrow is not drawn, in keeping with the original Arc design choice.

@r34gzilla: the popup menus are lacking shadows on top/left sides, due to what is apparently a bug in gnome shell, which won't render them (while it will render bottom/right shadows). Or at least I haven't been able to find a solution to have the `box-shadow` render on all 4 sides for popups ...
The original solution used (`border-image`) was definitely more elegant and had complete shadows, but will just not scale properly when display scaling is greater than 100% (due to another bug in gnome shell). So the current solution seems to me the lesser of two evils - unless and until bugs are fixed upstream. Other themes have done away with shadows completely in the shell due to the `border-image` scaling bug ...
