### ISSUE TITLE
unable to build latest git package without gnome-shell

### ISSUE THREAD

**Issue by macearl** [NicoHood/arc-theme#136]
Neither in the Readme nor in the PKGBUILD for the Arch Package is it mentioned that gnome-shell is a dependency for arc-theme (and the prebuilt version works fine without it)

```
checking for gnome-shell... no
        
configure: error: Could not find gnome-shell from $PATH.
configure: WARNING: cache variable ac_cv_prog_GNOME_SHELL_FOUND contains a newline
==> ERROR: A failure occurred in build().
```

Distribution: Arch Linux
Desktop environment: i3
Arc version: 20180715.r35.f53f43a-1
GTK3 version: 3.24.1+2+ged57e564a9-1
Installation method: Arch AUR

**Comment by NicoHood** [comment]
Do we really need this installed at build time?

**Comment by fossfreedom** [comment]
True - you don't have to - you can build with a specific gnome-shell version --with-gnome-shell=3.30

**Comment by NicoHood** [comment]
Then we should use this to avoid the build dependency.

**Comment by jnsh** [comment]
The check for gnome-shell version was added in #117, which also added it as an (optional) dependency.

As @fossfreedom mentioned, the dependency can be avoided by either not building the shell theme at all by using `--disable-gnome-shell` configure option, or defining the gnome-shell version manually using `--with-gnome=<version>`.

Fixing the dependencies in README slipped trough my mind due to some more pressing fixes, but I'll do it ASAP. I'll also try improving the error message from missing gnome-shell during configure.
