### ISSUE TITLE
Dash-To-Panel kinda broken after arc-theme update

### ISSUE THREAD

**Issue by Cerberooo** [NicoHood/arc-theme#217]
* Arch Linux
* Gnome 3.32 with Arc-Dark (WM) and Arc-Darker (GTK2/3)
* Theme installed from AUR (20190330-1)

There is a little space between the icons and the panel edge, which wasn't present before. I think this space causes the whole thing to glitch out of the screen. 

![image](https://user-images.githubusercontent.com/16780924/55275799-ba6cde80-52eb-11e9-8bcd-996619eabcf0.png)

**Comment by charlesg99** [comment]
Hello, this issue was introduced with the padding being replaced by margins in 4802bc1fb9270b4e830ccf8361703f4ff698cff4. 

This css:
```
.dash-item-container > StWidget, .dash-item-container > StWidget:rtl, .right .dash-item-container > StWidget {
  margin: 4px 8px;
  padding: 0; }

.top .dash-item-container > StWidget, .bottom .dash-item-container > StWidget {
  margin: 6px;
  padding: 0; }
```
gives 

![image](https://user-images.githubusercontent.com/33044886/55283942-d64ba100-533a-11e9-82f5-6abf451224db.png)
<br/><br/>
while this css:
```
.dash-item-container > StWidget, .dash-item-container > StWidget:rtl, .right .dash-item-container > StWidget {
  padding: 4px 8px; }

.top .dash-item-container > StWidget, .bottom .dash-item-container > StWidget {
  padding: 6px; }
```

gives

![image](https://user-images.githubusercontent.com/33044886/55283928-a4d2d580-533a-11e9-9d7e-8b1b185ebc9f.png)

Thanks!

**Comment by charlesg99** [comment]
@Cerberooo This style will now be overridden by dash-to-panel, so a quick fix for now could be to install the latest master from [over there](https://github.com/home-sweet-gnome/dash-to-panel). Thanks

**Comment by NicoHood** [comment]
Can we ignore the bug then?

**Comment by Cerberooo** [comment]
@charlesg99 Thanks for the fix!

@NicoHood I think so.

**Comment by FreddieChopin** [comment]
I'm having a similar problem with dash-to-dock extension. At least I think it is similar (; Generally when some more programs are opened dash expands, but this expansion seems to be a bit too small because of spacing between icons. Frequently some icons are not visible in the dash at all (they are completely "out" of the available space). When closing the apps, the situation does not improve completely, as the spacing between icons seems to keep increasing...

![Screenshot from 2019-04-02 23-53-34](https://user-images.githubusercontent.com/1139038/55438828-0301f180-55a3-11e9-9ed2-72cccc912e01.png)

Is this a problem in dash-to-dock extension or in arc theme? Thanks for the hints!
